CREATE FOREIGN TABLE T_HOMOGEN_MONTH (
  STNR BIGINT, 
  DATO DATE, 
  TDATO DATE, 
  SEASON SMALLINT, 
  RR DECIMAL(9,3), 
  RRA DECIMAL(5,1), 
  TAM DECIMAL(9,3), 
  TAMA DECIMAL(5,1), 
  EDIT_DATO DATE DEFAULT SYSDATE
) SERVER KDVH OPTIONS (table 'T_HOMOGEN_MONTH');

CREATE FOREIGN TABLE T_HOMOGEN_DIURNAL (
  STNR BIGINT, 
  TAM DECIMAL(5,1), 
  DATO DATE, 
  TAN DECIMAL(5,1), 
  TAX DECIMAL(5,1), 
  RR DECIMAL(7,1)
) SERVER KDVH OPTIONS (table 'T_HOMOGEN_DIURNAL');
