CREATE FOREIGN TABLE T_RR_RETURNPERIOD (
  STNR BIGINT, 
  LITRE_SEC_HECTAR DECIMAL(8,1), 
  DURATION SMALLINT, 
  RETURNPERIOD SMALLINT, 
  DEPENDENCY_OR_NOT VARCHAR(1)
) SERVER KDVH OPTIONS (table 'T_RR_RETURNPERIOD');

CREATE FOREIGN TABLE T_RR_INTENSITY (
  STNR BIGINT, 
  DATO DATE, 
  DURATION SMALLINT, 
  SEASON SMALLINT, 
  INTENSITY DECIMAL(8,6), 
  DEPENDENCY_OR_NOT VARCHAR(1), 
  FYEAR SMALLINT, 
  TYEAR SMALLINT
) SERVER KDVH OPTIONS (table 'T_RR_INTENSITY');