CREATE FOREIGN TABLE T_ELEM_PDATA (
  STNR              BIGINT, 
  ELEM_CODE         VARCHAR(10), 
  FDATO             TIMESTAMP, 
  TDATO             TIMESTAMP, 
  TABLE_NAME        VARCHAR(15), 
  FLAG_TABLE_NAME   VARCHAR(10), 
  AUDIT_DATO        TIMESTAMP DEFAULT CURRENT_DATE
) SERVER KDVH OPTIONS (table 'T_ELEM_PDATA');
