CREATE FOREIGN TABLE t_elem_map_timeseries (
  ELEM_CODE varchar(15) not null,
  STNR BIGINT NOT NULL,
  FROMDATE date not null,
  TODATE date,
  TABLE_NAME varchar(22),
  STANDARD_NAME varchar(100),
  CELL_METHOD varchar(100),
  OBSERVATION_TIMESPAN varchar(50),
  TIME_OFFSET varchar(50),
  SENSOR_NR smallint,
  SENSOR_LEVEL smallint,
  AUDIT_DATO date,
  ELEMENT_ID varchar(2000),
  LEVEL_UNIT varchar(100),
  FLAG_TABLE_NAME varchar(100),
  CODE_TABLE_NAME varchar(100),
  REFERENCE_TIME varchar(24),
  RESULT_TIMEINTERVAL varchar(5),
  INNER_CELL_METHOD varchar(100),
  LIMIT_INT decimal(5,2),
  COVERAGE_METHOD varchar(100),
  ELEMENT_COMPOSITION varchar(2000),
  HAS_ACCESS smallint,
  PERFORMANCE_CATEGORY varchar(100),
  EXPOSURE_CATEGORY varchar(100),
  ORG_TS_ELEM_TABLE varchar(100)
) SERVER KDVH OPTIONS (table 'T_ELEM_MAP_TIMESERIES');
