CREATE FOREIGN TABLE t_10minute_data (
 STNR BIGINT NOT NULL,
 DATO TIMESTAMP NOT NULL,
 DD SMALLINT,
 FF DECIMAL(5,1),
 RR_010 DECIMAL(5,1),
 RT_010 DECIMAL(5,1),
 TYPEID DECIMAL(5),
 TA DECIMAL(5,1),
 SA SMALLINT,
 RA DECIMAL(7,2),
 QSI_010 DECIMAL(7,2),
 TSS DECIMAL(5,1),
 FG_010 DECIMAL(5,1),
 VMOR INT,
 WAWA_015 SMALLINT,
 OT_010 SMALLINT,
 STATSA SMALLINT,
 SIGNSTR_SHM DECIMAL(5,1)
) SERVER KDVH OPTIONS (table 'T_10MINUTE_DATA');


CREATE FOREIGN TABLE T_10MINUTE_FLAG (
  STNR BIGINT, 
  DATO TIMESTAMP, 
  DD CHAR(5), 
  FF CHAR(5), 
  RR_010 CHAR(5), 
  RT_010 CHAR(5), 
  TYPEID INT, 
  TA CHAR(5), 
  SA CHAR(5), 
  RA CHAR(5), 
  QSI_010 CHAR(5), 
  TSS CHAR(5), 
  FG_010 CHAR(5), 
  VMOR CHAR(5), 
  WAWA_015 CHAR(5), 
  OT_010 CHAR(5), 
  STATSA CHAR(5), 
  SIGNSTR_SHM CHAR(5)
) SERVER KDVH OPTIONS (table 'T_10MINUTE_FLAG');
