CREATE FOREIGN TABLE T_NDATA (
  STNR INT, 
  DATO DATE, 
  ITR SMALLINT, 
  RR_24 DECIMAL(5,1), 
  SA SMALLINT, 
  SD SMALLINT, 
  V4 SMALLINT, 
  V4S SMALLINT, 
  V5 SMALLINT, 
  V5S SMALLINT, 
  V6 SMALLINT, 
  V6S SMALLINT, 
  KLOBS VARCHAR(12), 
  KLSTART VARCHAR(12), 
  RR_X DECIMAL(7,1), 
  TYPEID SMALLINT, 
  V_24 SMALLINT, 
  ORIG_OBSTIME DATE, 
  EE SMALLINT
) SERVER KDVH OPTIONS (table 'T_NDATA');


CREATE FOREIGN TABLE T_NFLAG (
  STNR INT, 
  DATO DATE, 
  ITR CHAR(5), 
  RR_24 CHAR(5), 
  SA CHAR(5), 
  SD CHAR(5), 
  V4 CHAR(5), 
  V4S CHAR(5), 
  V5 CHAR(5), 
  V5S CHAR(5), 
  V6 CHAR(5), 
  V6S CHAR(5), 
  KLOBS CHAR(5), 
  KLSTART CHAR(5), 
  RR_X CHAR(5), 
  TYPEID CHAR(5), 
  V_24 CHAR(5), 
  ORIG_OBSTIME DATE, 
  EE CHAR(5)
) SERVER KDVH OPTIONS (table 'T_NFLAG');
