CREATE FOREIGN TABLE T_SECOND_DATA (
  STNR INT, 
  DATO DATE, 
  RRVIPP DECIMAL(3,1), 
  TYPEID SMALLINT
) SERVER KDVH OPTIONS (table 'T_SECOND_DATA');


CREATE FOREIGN TABLE T_SECOND_FLAG (
  STNR INT, 
  DATO DATE, 
  RRVIPP CHAR(5), 
  TYPEID SMALLINT
) SERVER KDVH OPTIONS (table 'T_SECOND_FLAG');


CREATE FOREIGN TABLE T_MINUTE_DATA (
  STNR BIGINT, 
  DATO DATE, 
  TYPEID INT, 
  OT_1 SMALLINT, 
  QSI_01 DECIMAL(7,1), 
  QSO_01 DECIMAL(7,1), 
  QLO_01 DECIMAL(7,1), 
  QLI_01 DECIMAL(7,1), 
  TIQL DECIMAL(5,1), 
  QLINETINST_01 DECIMAL(7,3), 
  QLONETINST_01 DECIMAL(7,3), 
  OT_01 SMALLINT, 
  TIQS DECIMAL(5,1), 
  RI_01 DECIMAL(6,1)
) SERVER KDVH OPTIONS (table 'T_MINUTE_DATA');


CREATE TABLE T_MINUTE_FLAG (
  STNR BIGINT, 
  DATO DATE, 
  TYPEID INT, 
  OT_1 CHAR(5), 
  QSI_01 CHAR(5), 
  QSO_01 CHAR(5), 
  QLO_01 CHAR(5), 
  QLI_01 CHAR(5), 
  TIQL CHAR(5), 
  QLINETINST_01 CHAR(5), 
  QLONETINST_01 CHAR(5), 
  OT_01 CHAR(5), 
  TIQS CHAR(5), 
  RI_01 CHAR(5)
) SERVER KDVH OPTIONS (table 'T_MINUTE_FLAG');
